// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/zhangjun/AeroSpeech-ONNX",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "检查服务健康状态和组件状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "服务健康",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/monitor": {
            "get": {
                "description": "获取服务的实时监控数据，包括指标、资源和性能数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "获取实时监控数据",
                "responses": {
                    "200": {
                        "description": "监控数据",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "获取ASR、TTS、会话和资源的综合统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "获取综合统计信息",
                "responses": {
                    "200": {
                        "description": "统计信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/stt/batch": {
            "post": {
                "description": "批量识别多个音频文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "STT"
                ],
                "summary": "批量识别",
                "parameters": [
                    {
                        "description": "批量识别请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchRecognizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "识别成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/stt/config": {
            "get": {
                "description": "获取语音识别服务的配置信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "STT"
                ],
                "summary": "获取STT配置",
                "responses": {
                    "200": {
                        "description": "配置信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/stt/recognize": {
            "post": {
                "description": "上传音频文件进行语音识别",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "STT"
                ],
                "summary": "文件上传识别",
                "parameters": [
                    {
                        "type": "file",
                        "description": "音频文件",
                        "name": "audio",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "识别成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/stt/stats": {
            "get": {
                "description": "获取语音识别服务的统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "STT"
                ],
                "summary": "获取STT统计信息",
                "responses": {
                    "200": {
                        "description": "统计信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tts/batch": {
            "post": {
                "description": "批量将多个文本合成为语音音频",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TTS"
                ],
                "summary": "批量合成",
                "parameters": [
                    {
                        "description": "批量合成请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchSynthesizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "合成成功",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tts/config": {
            "get": {
                "description": "获取语音合成服务的配置信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TTS"
                ],
                "summary": "获取TTS配置",
                "responses": {
                    "200": {
                        "description": "配置信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tts/speakers": {
            "get": {
                "description": "获取可用的说话人列表及其信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TTS"
                ],
                "summary": "获取说话人列表",
                "responses": {
                    "200": {
                        "description": "说话人列表",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tts/stats": {
            "get": {
                "description": "获取语音合成服务的统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TTS"
                ],
                "summary": "获取TTS统计信息",
                "responses": {
                    "200": {
                        "description": "统计信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tts/synthesize": {
            "post": {
                "description": "将文本合成为语音音频",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "audio/wav"
                ],
                "tags": [
                    "TTS"
                ],
                "summary": "文本合成",
                "parameters": [
                    {
                        "description": "合成请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SynthesizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "音频文件",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务器错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.BatchRecognizeRequest": {
            "type": "object",
            "required": [
                "files"
            ],
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.BatchSynthesizeRequest": {
            "type": "object",
            "required": [
                "texts"
            ],
            "properties": {
                "texts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SynthesizeRequest"
                    }
                }
            }
        },
        "handlers.SynthesizeRequest": {
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "speaker_id": {
                    "type": "integer"
                },
                "speed": {
                    "type": "number"
                },
                "text": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "AeroSpeech-ONNX API",
	Description:      "基于Sherpa-ONNX的语音识别(STT)和语音合成(TTS)服务API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
